### ISSUE TITLE
Error when dispose FluentToast

### ISSUE THREAD

**Issue by LeticyaSheyla** [grbtec/gbt_fluent2_ui#1]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: setState() called after dispose(): _FluentToastAnimationState#571c4(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

#0      State.setState.<anonymous closure> (packag<…>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 207 pos 12: '_overlay != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:207:12)
#3      FluentToastOverlayEntry.remove (package:gbt_fluent2_ui/src/components/fluent_components/fluent_toast/fluent_toast_overlay_entry.dart:61:11)
#4      FluentToast._showOverlay.<anonymous closure> (package:gbt_fluent2_ui/src/components/fluent_components/fluent_toast/fluent_toast.dart:107:22)
#5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patc<…>

**Comment by railson-ferreira** [comment]
Fixed: a1d2dd10754cb5a4646c82ba83199c304080d5cc
