### ISSUE TITLE
Text field has a redundant bottom padding

### ISSUE THREAD

**Issue by hypen-flutter** [grbtec/gbt_fluent2_ui#2]
![image](https://github.com/user-attachments/assets/42795702-c35c-402f-a6bc-8aa144492785)

```dart
Row(
  children: [
    Expanded(
      child: FluentTextField(
        controller: newTodoTitleController,
        onSubmitted: (_) => createNewTodo(),
      ),
    ),
    const SizedBox(width: 12),
    FluentButton(
      onPressed: createNewTodo,
      title: 'Add',
    ),
  ],
);
```
Text input is not aligned to the bottom of the `FluentTextField`

**Comment by LeticyaSheyla** [comment]
Hello [@hypen-flutter](https://github.com/hypen-flutter), thanks for the report and for using our package!👋🏼

The issue was fixed in this new release: [6.0.14](https://github.com/grbtec/gbt_fluent2_ui/releases/tag/v6.0.14). 

Can you tell us how you found our library?

**Comment by hypen-flutter** [comment]
@LeticyaSheyla  I have confirmed that the issue has been resolved. 
 I wanted to use Fluent2 UI design systems, so I searched `fluent2` on pub.dev. I found yours and `fluent_ui`. 
`fluent_ui`'s design is not up-to-date, so I decided to use yours.

**Comment by LeticyaSheyla** [comment]
Thanks for using our package, I hope you enjoy it!

**Comment by LeticyaSheyla** [comment]
Thanks for using our package, I hope you enjoy it!
